### ISSUE TITLE
Suggestion: Track WorldEdit placed blocks as creative placed.

### ISSUE THREAD

**Issue by ArtNRG** [Prunt/RestrictedCreative#1]
Many server owners give their players WorldEdit commands along with creative game mode. Please track blocks that are placed with WorldEdit (//set diamond_block) and it will be the best limit plugin ever!

**Comment by Prunt** [comment]
I'll definitely look into it when I start developing the next version. Thanks for the suggestion!

**Comment by Prunt** [comment]
Added in 1.9.0!
