### ISSUE TITLE
PlayerVaults

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#13]
Players can't open PV's but the pv gets cleared for no reason and if I want to disable to open the pv's I have to do - 'pv 1' - 'pv 2' pls can you make it that it will disable that too

**Comment by EvilSlime** [comment]
So like disable command completion after it

**Comment by Prunt** [comment]
What does the PlayerVault not opening and clearing problem has to do with RestrictedCreative? You can just add 'pv (.*)' to disabled command list to disable all commands starting with "pv ".
