### ISSUE TITLE
Mob Interaction

### ISSUE THREAD

**Issue by CryptoMorin** [Prunt/RestrictedCreative#14]
Here are the list of mobs that players can hit when they're in creative:
- Squid
- Shulker
- Slimes
- Magma Slimes
- Villager Golem
- Enderdragon

Not sure if there is more.

Tested it in a completely empty server and i can still hit those mobs. 
I tested this myself using `EntityDamageByEntityEvent` and cancelled it, worked just fine.
Even removed `MONITOR` event priority flag from the event and it still worked fine.
Are you using anything else? Idk.

And btw, just to let you know I'm using `Spigot v.1.12.2` using `Restricted Creative 1.12.2`. (Like i said before there was a server owner who bought the plugin not me, so i just still have it. And i can no longer contact the person to download the new version for me.) So I'm not pretty sure if it's the outdated version that is causing the issue but i checked every single update log from `v1.12.2` and reported issues and none of them included this issue.

**Comment by Prunt** [comment]
This was fixed in 1.12.4: `FIXED - slimes, magma cubes (and possibly other creatures) are now protected from creative players' wrath from now on (thanks @andris155 )`
