### ISSUE TITLE
Ending up toggling between 3 inventories

### ISSUE THREAD

**Issue by ResqDiver1317** [Prunt/RestrictedCreative#18]
Our server owner added this plugin and I was testing it for him last night. 
The issue I'm seeing is that I'm ending up with 3 different inventories. I'll outline how I'm seeing them.
1.Start in survival with survival inv.
2.Switch to creative and get empty inventory as expected. Use creative mode a bit and get a "creative inventory"
3.Switch back to survival and get a new empty inventory.
4.Switch back to creative and get my original Survival Inventory.
5.Switch back to survival and get my creative inventory.
6.Switch back to creative and get that 3rd inventory.
7.Switch back to survival and get my original Survival Inventory. 

I tested with 2 different players and was getting this pattern every time. 

I saw there was a closed issue where someone referenced the PerWorldInventories causing a problem because they were using it in a separate world for creative but the issue was closed because the OP never replied. I'm wondering if PWI is causing the issue here as well possibly. We are not using this in a separate world like that person did, we will be using this in our survival world, but we are using PWI because we have a survival world and a SkyBlock world and PWI is keeping those inventories separated.

**Comment by Prunt** [comment]
Could you confirm that the PWI plugin is causing the problem by removing it and testing the inventory swiching again? Then I can look into it and see if I can do anything about it.

**Comment by ResqDiver1317** [comment]
I'll download a copy of our server so I can test this tomorrow without affecting our other players. As soon as I have it tested, I'll report my results.

**Comment by ResqDiver1317** [comment]
Ok, I fired up the backup I made of our server deleting the RC Database between each attempt. The backup with PerWorldInventory enabled did the exact same thing (as I expected since it was a direct copy of our server). I shut down, deleted the RC Database again, disabled PWI, and fired back up. This time the RC was handling inventory as it should with no issues. 
This pretty much confirms the issue has something to do with RC and PWI both interacting with a players inventory.

**Comment by Prunt** [comment]
Sorry for the late reply, I was on holiday.

I tested it and tried to come up with some kind of solution, but unfortunately I couldn't. I'll contact the PWI developer and let you know.

**Comment by ResqDiver1317** [comment]
We appreciate your help! Hopefully the PWI dev can offer some insight and help with a solution

**Comment by Prunt** [comment]
Unfortunately, I haven't had any luck contacting the author via PM. I'll create a new issue in the PWI GitHub page.

**Comment by Prunt** [comment]
The author responded with a helpful answer: https://github.com/Gnat008/PerWorldInventory/issues/312#issuecomment-372084609

**Comment by ResqDiver1317** [comment]
Oh yea, that worked much cleaner. I did see one issue that still remains and is most likely still a conflict between how RC and PWI work, but TBH, now that this major issue is resolved, I'm not sure the new issue I discovered is worth the trouble of messing with unless there is an easy way to config around it in one of the plugins. Basically, if you are in GM1 in the survival world, and you go to the skyblock world, it puts you back in survival, which is as intended as we are going to only allow creative in survival, but when you go back to the survival world, you are in GM0 but have your GM1 inventory. Toggling to GM1 gives you your GM0 inventory back, but since you cannot access chests, there is no way to retain it.  

I think this issue is related to the combination of PWI saving your inventory for the world you left as well as the server forcing your gamemode based on the world, not your last state. Since the survival world is defaulted to GM0, you are forced into GM0 when you return to the world even though you left it in GM1, but PWI has your exit inventory saved that you had on you, which happens to be your GM1 inventory.  Again, although this can be an annoying issue, A simple statement in our server info saying something to the effect of "Be sure to return to Gamemode 0 before changing worlds or your inventory will likely be lost and we will not recover it for you". Most players (at least the ones in our community), will take that instruction and follow it. 

I am going to try and mess around with our plugins and see which one is forcing the gamemode per world (most likely Multiverse) and see if I can get it to not force the gamemode in Survival world. If so, that may resolve this issues as it will "hopefully" return them to the gamemode they were in when they left that world. Due to the nature of this new issue being related potentially to the actions of several plugins, I def do not expect you to work up a solution (although if you have ideas, it would be appreciated :)  ), Mainly, I just wanted to make you aware of it in case anyone else come to you with a similar problem.

Above all, Thanks for finding a solution to the main issue we were having!! We have several players who are dying to use creative mode and pending a warning about changing worlds being posted on our Info Page, we can now open Restricted Creative up to our community!

**Comment by ResqDiver1317** [comment]
OH! Disregard like 90% of the above statement. I just remembered I can set commands to be blocked while in RC's creative mode. I'll just block access to /home, /is, /warp, and /tp which will remove all ability to jump between worlds and then there will no issue at all!! You fixed my problem before I even knew I had it!

**Comment by Prunt** [comment]
Glad to hear! Let me know if you have any other problems.
