### ISSUE TITLE
1.12 Inventory Saving

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#21]
People can get like Money Vouchers on their own server and use them by saving the GMC inventory. This caused a huge economy exploid is there any way you can solve this?

**Comment by Prunt** [comment]
I'll add some settings on which items to confiscate from creative players so you could define how RestrictedCreative should know what exactly are Money Vouchers. Wait for the next version.

**Comment by Prunt** [comment]
Check out the configuration options: https://github.com/Prunt/RestrictedCreative/wiki/Config-explanation
