### ISSUE TITLE
WitherBoss Patterns Bypass

### ISSUE THREAD

**Issue by CryptoMorin** [Prunt/RestrictedCreative#27]
You can summon a witherboss in different ways other than doing the following pattern below:

           *  *  *
           |   |   |
               |
               |

(| = Soul Sand, * = Wither Skeleton Skull)

See the screenshot below for two other simple patterns that my donator found.
![2018-05-08_18 26 55](https://user-images.githubusercontent.com/25098093/39775789-70d8915e-52ee-11e8-8326-2ae884b5dc8b.png)

**Comment by Prunt** [comment]
That's something I didn't know about Minecraft... cool. 😄
I'll fix it in the next update.
