### ISSUE TITLE
Farm glitch

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#29]
If you make a farm in GMC and it grows it will remove the whole item/farm. https://www.youtube.com/watch?v=GhJHVOyA7Ro

**Comment by Prunt** [comment]
How exactly can I reproduce the problem? I tried to create a cactus farm in creative mode, but when the cactus tried to grow, it just dropped the item as it should.

**Comment by Prunt** [comment]
I'm closing the issue for now, feel free to reopen it when you can provide more information.
