### ISSUE TITLE
Problems with interact inventories

### ISSUE THREAD

**Issue by AIphaDragon** [Prunt/RestrictedCreative#30]
Hi! If you set these settings, you can not use the chests in creative mode:

disable:
    interact:
      inventories: true

But even then it will not be possible to open any GUI menu on the server. For examle: /menu, /donate, /rules, /info. Is there any way to fix this? Thank you in advance.

**Comment by Prunt** [comment]
If this setting is true, creative players can't interact with inventories, which includes chests and other GUIs. If you want to allow GUIs that can be opened with commands, then you'll have to blacklist chests, furnaces and all other blocks that can open an inventory with a right click.
