### ISSUE TITLE
Bed protection not work (Paper 1.12.2)

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#33]
https://www.youtube.com/watch?v=KiJHID75z2I

**Comment by Prunt** [comment]
Any errors in the config? Have you tested it without other plugins? I tested it on Spigot 1.12.2 an it worked fine, Paper should behave the same.

**Comment by Ridys** [comment]
Hi all, I have same core and this problem. I tested the server and found that this bug calls the plugin named Jobs Reborn. 
Also I know about the bug with boats (protection does not work properly, tested on clean core).
Is it possible to do something about this? Thanks.

**Comment by Prunt** [comment]
Yup, I installed Jobs and a bed popped out. :smile: 

I tested boats as well, but they worked fine. How exactly doesn't the protection work?
