### ISSUE TITLE
Door, magma cube protection bug (Paper 1.12.2)

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#34]
https://www.youtube.com/watch?v=nnwABLdOzsQ
https://www.youtube.com/watch?v=n_Y2Kd43dzU

**Comment by Prunt** [comment]
I remember fixing the magma cubes once before, I guess I'll have to do it again then. :smile: 
I tested breaking doors on latest Paper 1.12.2 with RC 1.14.2 release candidate and I didn't have any problems with it. Maybe it'll be fixed in the next version.

**Comment by Prunt** [comment]
I probably found a fix for the doors as well, test the next version.
