### ISSUE TITLE
Bug with lava bucket

### ISSUE THREAD

**Issue by baticag** [Prunt/RestrictedCreative#39]
Demonstrated in the video:
https://www.youtube.com/watch?v=QH-R0yCjdiY

**Comment by Prunt** [comment]
What Spigot/Paper version are you using? I tested it on Spigot 1.12.2 with RC 1.15.2 and couldn't reproduce the bug.

**Comment by Prunt** [comment]
I'm going to close this for now. If you have additional information to give me, feel free to reopen.
