### ISSUE TITLE
No Inventory Separation - BUG with Error

### ISSUE THREAD

**Issue by Faicu** [Prunt/RestrictedCreative#4]
When I try to change gamemode, from creative to survival or vice-versa, there is no separation, but, it's a error on console:
https://paste.md-5.net/xoheboyale.avrasm

**Comment by Prunt** [comment]
Well. This certainly seems "interesting" to say the least. I can't reproduce it on my testserver.

What command did you use to switch game modes? What server version are you running?

**Comment by Faicu** [comment]
Spigot 1.12.1 - Latest Build
/gm 1 and /gm 0 ...

**Comment by Prunt** [comment]
Strange... Server restart doesn't help? Are you testing this on a newly created server?

**Comment by Faicu** [comment]
No, the server it's not new, running for 2-3 years, I put the plugin on server, togheder RestrictedCreative folder and inside it config.yml. configured from default config from github... Database it's working ok, all it's working good, except that...

**Comment by Prunt** [comment]
Try creating a new testserver on your PC with the latest Spigot and try the command again. Also, updating Java on your main server might help as well.

**Comment by Faicu** [comment]
Java it's latest version... 
Can it be because EssentialsX?
If I will do a server on my pc, probably it will work correctly, but this will not help me...

**Comment by Faicu** [comment]
This plugin is working 99% correctly, only this inventory separation is a problem...

**Comment by Prunt** [comment]
It shouldn't be EssentialsX's fault, in fact none of the plugins shouldn't cause this error.

Did you test it on a newly created testserver as well?

The error itself doesn't make any sense though, seems more like a compilation mismatch. I could add some features and recompile the next version, maybe that helps.

**Comment by Faicu** [comment]
Have you did that on latest update?

**Comment by Prunt** [comment]
Yup, I recompiled it. Does the 1.8.0 work for you?

**Comment by Prunt** [comment]
@Faicu Any updates on that issue? I've released 1.9.0 as well, which you can test.

**Comment by lilacorn** [comment]
i can vouch for this problem too. if someone goes from survival to creative mode then back to survival, they lose all their items into creative and stuck with red armor in survival with a block. not seeing any errors popping up in mymcadmin console. i have 1.12.2 spigot with latest version of RC 1.9.0 Sep. 17th.

**Comment by Prunt** [comment]
@lilacorn Do you have the same error in the console? If not, you should make a separate bug report.
