### ISSUE TITLE
ArmorStand head slot

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#47]
How to disable access players ArmorStand head slot creative mode?

**Comment by andris155** [comment]
And how to block access ArmorsStand hand?
https://m.imgur.com/a/Nv3lgJy

**Comment by Prunt** [comment]
Do you really need to block access to specific EquipmentSlots? Couldn't disabling interactions with the whole armor stand be enough?

> https://imgur.com/a/Nv3lgJy
This will be fixed in the next version.
