### ISSUE TITLE
Fence bug

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#49]
1. Place block and lever, button etc...
2. Break block.
3. Place fence.
4. Dropped creative items.

![image](https://user-images.githubusercontent.com/36449228/44595958-f0346c80-a7ca-11e8-8880-8e7e5e6469d4.png)
![image](https://user-images.githubusercontent.com/36449228/44596001-0e01d180-a7cb-11e8-9f3b-b5398a854ac7.png)
![image](https://user-images.githubusercontent.com/36449228/44596011-1528df80-a7cb-11e8-92c1-e7df025a344d.png)

**Comment by Prunt** [comment]
I tested it on my testservers (prunt2.nuhvel.eu (1.12.2) is running v1.15.6 and prunt.nuhvel.eu (1.13.1) has v2.0b), but I couldn't reproduce the issue. What version of Spigot and RestrictedCreative are you using? Have you tried removing all other plugins and see if the bug persists?

**Comment by andris155** [comment]
This server is running Paper version git-Paper-1551 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
RestrictedCreative version 1.15.6
