### ISSUE TITLE
Can drop creative items in survival chest

### ISSUE THREAD

**Issue by Swede37** [Prunt/RestrictedCreative#5]
Scenario: We have a WorldGuard zone flagged as "creative".  A player who is just outside this zone, in the survival area, can place a chest / enderchest close to the edge of the zone.  When they are in the creative area, they stock up their inventory (ie 64 stack of diamonds).
Then, they go back into the survival zone - and  they run to the creative region.  Just a second before they enter the Creative zone, they open the chest.  Because you don't stop instantly, they slide a little further (just into the Creative area) about .25 block.  The chest is still open, but they have creative inventory, so they can put the *free stuff* (ie that stack of diamonds) into the chest / enderchest.  Then, they can take out the items next time they are back into survival.

Yes, one of my players was fast enough to do this repeatedly!  Luckily he was staff, testing for things like this.
Using:  latest version Spigot & RestrictedCreative, WorldGuard, and several other plugins.

**Comment by Prunt** [comment]
It seems to have the same principle as a hacker who opens a chest in survival mode, runs /rc in the background using the hack and shovels stuff into that chest. I had a check in place for that, but it doesn't apparently work. I'll figure something out for the next version.

**Comment by Prunt** [comment]
I added a check in v1.10.0 that doesn't allow switching to creative mode when any kind of inventory is opened, which should fix the issue.
