### ISSUE TITLE
Water bug

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#53]
RestrictedCreative 2.0c-BUGGY
https://www.youtube.com/watch?v=fx7TmWDxKxY

**Comment by andris155** [comment]
Same redstone torch, redstone repeater, redstone comparator, torch, redstone, all sapling, all flowers, red mushroom, brown mushroom, end rod

**Comment by Prunt** [comment]
Buttons, dead bush, fern, grass are affected as well.

Carpets have some magic aura sometimes, keeping water away from them.
