### ISSUE TITLE
PerWorldInventory

### ISSUE THREAD

**Issue by kiritss** [Prunt/RestrictedCreative#6]
I use a plugin called PerWorldInventory in order to have a creative world. Having a creative world + perworldinventory with restrictedcreative really screws up the inventories and they often don't load properly

**Comment by Prunt** [comment]
Can you be more specific? I need the exact steps to reproduce the problem, only then I can work out what is causing it.

**Comment by Prunt** [comment]
Closing the issue due to no answer.
