### ISSUE TITLE
Error on saving data ?

### ISSUE THREAD

**Issue by MatinDark** [Prunt/RestrictedCreative#66]
hello I just found this error when try saving on database
https://hastebin.com/yisaxuqeku.md

I am using retired creative version 1.15.6

**Comment by Prunt** [comment]
Did this happen only once or is it a recurring error, even after restart?

**Comment by MatinDark** [comment]
each time try to save data

**Comment by Prunt** [comment]
Could you post the _database_ section of your config? You can omit username, password and host, they're not relevant.

**Comment by MatinDark** [comment]
Here you are https://paste.ubuntu.com/p/SR48TXn9hC/

**Comment by Prunt** [comment]
It seems that you're using RC 2.0 config with RC 1.15.6. They're not compatible, please rename your current config file and let it generate a new one.
