### ISSUE TITLE
Water + sponge break remove creative blocks

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#77]
2.0d-LESS-BUGGY
https://www.youtube.com/watch?v=7goGLhC3Qg4

**Comment by hankur** [comment]
Something weird is going on there. When I placed slabs under water, some of them would be waterlogged and some would not. Sponge only destroys waterlogged slabs, but sometimes turns them into non-waterlogged slabs. The new non-waterlogged slabs would then sometimes disappear one-by-one.
![2018-10-11_09 19 25](https://user-images.githubusercontent.com/10405384/46784822-47b97800-cd38-11e8-83ed-2b3959a4369d.png)
