### ISSUE TITLE
Dupe items from brewing stand

### ISSUE THREAD

**Issue by ungermum** [Prunt/RestrictedCreative#79]
Just watch the video https://youtu.be/3d0pivVKRHo

**Comment by hankur** [comment]
What version are you using (1.x or 2.x)?

**Comment by ungermum** [comment]
@hankur version 1.15.7

**Comment by hankur** [comment]
It seems that you have OP or bypass permissions. I tested it and normal player's can't access brewing stands and duplicate them (with items inside) with middle-click.

**Comment by ungermum** [comment]
Bad check.  All creative players don't have OP or bypass permissions.
You're probably using a different version.
Please fix the bug.

**Comment by hankur** [comment]
I tested it with RC 1.15.7 and Spigot 1.12.2. What Spigot version did you use?

**Comment by ungermum** [comment]
@hankur spigot 1.12.2

**Comment by hankur** [comment]
Well, have you tried removing other plugins and resetting the config?

**Comment by ungermum** [comment]
I use an empty server with default plugin config. but it doesn't help. The problem is NBT tag on brewing stand.

**Comment by hankur** [comment]
This must be an issue on on your half.
1. I created a new Spigot 1.12.2 server
2. installed RestrictedCreative
3. logged in and changed my gamemode to creative from the console
4. placed a brewing stand and tried to open it, but I can't do that in creative.

Please repeat those steps and let me know.

**Comment by ungermum** [comment]
1. I created a new Spigot 1.12.2 server
2. installed RestrictedCreative
3. logged in and changed my gamemode to creative from chat
4. take NBT brewing stand from saved toolbars. 
5. placed a brewing stand and break it
6. from NBT brewing stand dropped ghast tears.

**Comment by hankur** [comment]
Okay, I see the problem now. I'll come up with a solution in the next week.

**Comment by andris155** [comment]
Use this plugin disable nbt copy: https://www.spigotmc.org/resources/creative-nbt-copy-control.13598/

**Comment by ungermum** [comment]
@andris155 thx

**Comment by hankur** [comment]
I can't seem to replicate this anymore. I'm using Spigot 1.12.2 and RC 1.15.7.

The problem is that I can't get a brewing stand with items to my hotbar when middle-clicking on it in singleplayer - it gives me a regular breing stand instead. So I saved a shulker box with items instead, but when I loaded it in the server, it didn't have any items inside anymore.
