### ISSUE TITLE
RestrictedCreative on IridiumSkyblock

### ISSUE THREAD

**Issue by AndyGamming** [Prunt/RestrictedCreative#83]
Hi, nice job with this plugins, but I have a question.
I tried to run this plugin on a SkyBlock server, it's working just fine, but I keep getting an error in the console

https://pastebin.com/GR4aBHpg

**Comment by hankur** [comment]
Hi!

It seems that you're using RC 2.x on Spigot 1.12.x, which isn't supported. Use the latest RC 1.x instead.
