### ISSUE TITLE
Composts

### ISSUE THREAD

**Issue by Syrkulous** [Prunt/RestrictedCreative#84]
Composts can be used from creative menu

Option that denies use of herbs in composts

(I don't want to have to ban the usage of flowers for decoration, only from composts)

**Comment by hankur** [comment]
Please use our [Bitbucket Issues](https://bitbucket.org/Prunt/restrictedcreative/issues?status=new&status=open) page for problems with RC v2.x. This GitHub page is only for RC v1.x support.

Said that, you can add "COMPOSTER" under "disable.interacting.on-ground" in the config to stop creative players from adding stuff into the composter. I'll add it to the default config in the next version.

**Comment by Syrkulous** [comment]
Thank you, apologies, I didn't see anywhere else to report issues and github was the only place I'm use to, to do that
