### ISSUE TITLE
bug with fawe

### ISSUE THREAD

**Issue by wafumoon** [Prunt/RestrictedCreative#86]
if player place block and after this //set 0 it and after //undo block can be mining and drop

**Comment by hankur** [comment]
Do you have "general.worldedit.enabled" and "general.worldedit.extended" set to true?

**Comment by wafumoon** [comment]
yes.
Plugin log all worldedit commands nice, but not undo

**Comment by hankur** [comment]
Okay. What version of Spigot, RC and FAWE are you using? I'll see if I can reproduce this.

**Comment by wafumoon** [comment]
latest paper build for 1.12.2
Latest RC for 1.12.2 (1.15.7)
FastAsyncWorldEdit-bukkit-19.11.13-5505943-1282-22.3.5 (latest for 1.12.2)

**Comment by hankur** [comment]
After meddling with this for 4 hours I came to the conclusion that there isn't an easy way to support //undo in general:
1. I didn't find a way to get the blocks affected by //undo (WE API docs are truly horrible/missing);
2. to support more //undo's than one, I'd have to invent a way to save block changes for like... forever.

For now, my recommendation is to not use //undo or disable "general.worldedit.enabled" entirely.
