### ISSUE TITLE
Items are deleted from an inventory that should not be deleted

### ISSUE THREAD

**Issue by MegaNoam** [Prunt/RestrictedCreative#88]
Greetings,
We've been having a problem with the plugin for a long time
There is a possibility of deleting items from Inventory but the problem we experience with it is that it deletes items from Inventory that it should not delete from there (from unique plugins we use)
Is there a way to deal with the problem?

Thanks in advance
MegaNoam

**Comment by hankur** [comment]
What version of Spigot and RC are you using?

**Comment by MegaNoam** [comment]
**Spigot Version:**
`Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

**RestrictedCreative Version:**
`2.4.2`

**Comment by hankur** [comment]
Then this bug report doesn't belong here. GitHub is for RC v1 issues. I replied to you in the SpigotMC forums plugin Discussion page.
