### ISSUE TITLE
Skipped item: No enum constant org.bukkit.Material.ZOMBIE_PIGMAN_SPAWN_EGG

### ISSUE THREAD

**Issue by skmd0** [Prunt/RestrictedCreative#90]
We are getting error:
`Skipped item: No enum constant org.bukkit.Material.ZOMBIE_PIGMAN_SPAWN_EGG`

Using version 2.4.3 of RestrictedCreative

The error randomly appears and when it does it spams the console with these errors.

![unknown](https://user-images.githubusercontent.com/52122032/97574400-7839e080-19eb-11eb-8cfa-585d23888631.png)

The reason why I am reporting this here is because after we unload the plugin the errors stop.

![unknown2](https://user-images.githubusercontent.com/52122032/97574541-ab7c6f80-19eb-11eb-8f8f-06c953093e1c.png)

**Comment by newjebv** [comment]
+++ A similar situation, also damage is also carried out both with hands and with the help of an object in essence. If earlier it was impossible to beat, now it can be done calmly

**Comment by hankur** [comment]
What versions of Spigot and RC are you using? This GitHub repository is for RC v1 (latest 1.15.7). If you're usig RC v2, please refer to [BitBucket](https://bitbucket.org/Prunt/restrictedcreative/issues?status=new&status=open).

This simply means that your version of Spigot doesn't have an item named `ZOMBIE_PIGMAN_SPAWN_EGG`. You have to replace it with an alternative that does exist in your version.

@NewJeb Issues with dealing damage is a separate issue, please create a new issue and provide both versions and your config.

**Comment by skmd0** [comment]
We are using version 2.4.3 of RestrictedCreative and latest Paper (Spigot) version.

I assume that entity was removed in MC 1.16 update.

>If you're usig RC v2, please refer to BitBucket.

Will do when I create a BitBucket account. Thanks!
